### ISSUE TITLE
Default jobstats-configuration.ini

### ISSUE THREAD

**Issue by ZwFink** [nauhpc/jobstats#31]
I recently graduated from NAU and moved to a new institution with a SLURM-based campus cluster. When setting up the jobstats script for myself, I was getting errors that ```jobstats-configuration.ini``` was not found. I was working to set one up, but from this repository's README.md, it's not clear what each of the parameters do. I was able to grab the ```jobstats-configuration.ini``` that's on Monsoon and use it, but it would be nice if a configuration script with reasonable defaults were included in the repo.

**Comment by jguzman-tech** [comment]
Hi are you still interested in this?

For using jobstats we have several parameters that tell the script what colors to use for the output and how to count statistics. We also have DB info for some related scripts that will record some sacct statistics into a mysql DB.

**Comment by ZwFink** [comment]
I am interested in this still. I think it would be nice to have a configuration file with reasonable defaults that is shipped with this repository. It would make the ```jobstats``` script immediately usable from the repository. 

As it stands, one must first discover that ```jobstats-configuration.ini``` is not found by the script and then must obtain this configuration file.

**Comment by jguzman-tech** [comment]
Right, that's a simple request. jobstats is essentially a wrapper for the sacct command and includes running job info via sstat. There's no reason for it to fail if this jobstats-configuration.ini doesn't exist. I'll take a deeper look soon.

**Comment by ZwFink** [comment]
Looks like it is required implicitly by the setup process (not sure if it's required afterwards:
```bash
(charm4py) login1.stampede2(1066)$ git clone https://github.com/nauhpc/jobstats.git
(charm4py) login1.stampede2(1067)$ cd jobstats/
(charm4py) login1.stampede2(1069)$ python3 -m pip install --user .
...
  error: can't copy 'jobstats/jobstats-config.ini': doesn't exist or not a regular file
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home1/08302/tg876011/miniconda3/envs/charm4py/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4duaymv0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4duaymv0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cfwy4znl/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home1/08302/tg876011/.local/include/python3.9/jobstats Check the logs for full command output.

```

I truncated the above to show only relevant output.

**Comment by jguzman-tech** [comment]
Pretty sure that's fixed in: https://github.com/jguzman-tech/jobstats/blob/master/jobstats/jobstats

But will push it to this repo later

**Comment by ZwFink** [comment]
This doesn't seem to fix the issue. The crash happens in ```setup.py``` when trying to install jobstats. It requires the existence of the ```jobstats-config.ini``` file.

**Comment by jguzman-tech** [comment]
Sorry for the delay, made an edit and confirmed via a pip install this time

**Comment by jguzman-tech** [comment]
It's been merged here
